- hosts: localhost
  become: false
  vars:
    projects_directory: ~/Work
  tasks:
    - name: Install Oh My Zsh
      shell: |
        if [ ! -d ~/.oh-my-zsh ]; then
          curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
        fi
      tags:
        - zsh

    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: yes
        upgrade_all: yes
      tags:
        - homebrew

    - name: Install NVM
      homebrew: name=nvm
      tags:
        - node

    - name: Test for NVM installation
      shell: |
        if [ -z ${NVM_DIR+x} ]; then
          true
        fi
      register: test_nvm
      tags:
        - node

    - name: Adding NVM to path
      lineinfile:
        path: ~/.zshrc
        line: |
          # Inserted by build script
          export NVM_DIR="$HOME/.nvm"
          [ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"
          [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"
      when: test_nvm.stdout == "0"
      tags:
        - node

    - name: Install Yarn
      homebrew: name=yarn
      tags:
        - node

    - name: Install Docker
      homebrew_cask: name=docker
      tags:
        - docker

    - name: Homebrew tap aws/tap
      homebrew_tap:
        name: aws/tap
      tags:
        - sam

    - name: Install SAM Cli
      homebrew: name=aws-sam-cli
      tags:
        - sam

    - include: tasks/dunelm-web.yml
    - include: tasks/settlement-service.yml
    - include: tasks/basket-service.yml
    - include: tasks/store-locator.yml
    - include: tasks/store-locator-service.yml
    - include: tasks/payment-service.yml
