- hosts: localhost
  become: false
  vars:
    projects_directory: ~/Work
  tasks:
    - name: Install Oh My Zsh
      shell: |
        if [ ! -d ~/.oh-my-zsh ]; then
          curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
        fi
      tags:
        - zsh

    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: yes
        upgrade_all: yes
      tags:
        - homebrew


    - name: Test for NVM installation
      shell: |
        if [ -z ${NVM_DIR+x} ]; then
          true
        fi
      register: test_nvm
      tags:
        - node

    - name: Install NVM
      homebrew: name=nvm
      when: test_nvm.stdout == "0"
      tags:
        - node

    - name: Adding NVM to path
      lineinfile:
        path: ~/.zshrc
        line: |
          # Inserted by build script
          export NVM_DIR="$HOME/.nvm"
          [ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"
          [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"
      when: test_nvm.stdout == "0"
      tags:
        - node

    - name: Install Yarn
      homebrew: name=yarn
      tags:
        - node

    - include: tasks/dmg-install.yml appName=Docker dmgURL=https://desktop.docker.com/mac/main/arm64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=dd-smartbutton&utm_location=header
      tags:
        - docker

    - name: Homebrew tap aws/tap
      homebrew_tap:
        name: aws/tap
      tags:
        - sam

    - name: Install SAM Cli
      homebrew: name=aws-sam-cli
      tags:
        - sam

    - include: tasks/repo-install.yml name=dunelm-web repo=git@gitlab.com:dunelm/product/frontend/dunelm-web.git
      tags:
        - frontend

    - include: tasks/repo-install.yml name=store-locator-app repo=git@gitlab.com:dunelm/product/frontend/store-locator-app.git
      tags:
        - frontend

    - include: tasks/repo-install.yml name=settlement-service-aws-stacks repo=git@gitlab.com:dunelm/product/backend-services/settlement-service-aws-stacks.git
      tags:
        - backend

    - include: tasks/repo-install.yml name=basket-service-aws-stacks repo=git@gitlab.com:dunelm/product/backend-services/basket-service-aws-stacks.git
      tags:
        - backend

    - include: tasks/repo-install.yml name=storelocator-service-aws-stacks repo=git@gitlab.com:dunelm/product/backend-services/storelocator-service-aws-stacks.git
      tags:
        - backend

    - include: tasks/repo-install.yml name=payment-service-aws-stacks repo=git@gitlab.com:dunelm/product/backend-services/payment-service-aws-stacks.git
      tags:
        - backend
