- hosts: localhost
  become: false
  tasks:
    - name: Install Oh My Zsh
      shell: |
        if [ ! -d ~/.oh-my-zsh ]; then
          curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
        fi
    - name: Install NVM
      homebrew: name=nvm
    - name: Test for NVM installation
      shell: |
        if [ -z ${NVM_DIR+x} ]; then
          true
        fi
      register: test_nvm
    - name: Adding NVM to path
      lineinfile:
        path: ~/.zshrc
        line: |
          # Inserted by build script
          export NVM_DIR="$HOME/.nvm"
          [ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"
          [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"
      when: test_nvm.stdout == "0"
    - name: Clone Dunelm-Web
      ansible.builtin.git:
        repo: git@gitlab.com:dunelm/product/frontend/dunelm-web.git
        dest: ~/Work/dunelm-web/
      tags:
      - web
    - name: Install Dunelm-Web
      shell: |
        cd ~/Work/dunelm-web/
        yarn bootstrap
      tags:
      - web
    - name: Clone Settlement
      ansible.builtin.git:
        repo:
          git@gitlab.com:dunelm/product/backend-services/settlement-service-aws-stacks.git
        dest: ~/Work/settlement-service-aws-stacks/
      tags:
      - web
    - name: Install Settlement
      shell: |
        cd ~/Work/settlement-service-aws-stacks/
        yarn bootstrap
      tags:
      - settlement
