- name: Clone Basket Service
  ansible.builtin.git:
    repo: git@gitlab.com:dunelm/product/backend-services/basket-service-aws-stacks.git
    dest: "{{ projects_directory }}/basket-service-aws-stacks/"
    update: no
    accept_hostkey: true
  tags:
    - bs

- name: Install Basket Service packages
  ansible.builtin.shell: yarn bootstrap
  args:
    chdir: '{{ projects_directory }}/basket-service-aws-stacks/'
  tags:
    - bs
